#!/usr/bin/env python3
"""
Convert an image file to a 320×240 RGB565 C header for embedding as a
Robot36 SSTV test pattern. Output: a `static const uint16_t` array the
firmware can memcpy into the SSTV image buffer.

  usage:  image_to_rgb565.py SRC OUT [WIDTH] [HEIGHT]
  example: image_to_rgb565.py SSTV_test_image.jpg main/test_image.h
"""
import sys
from PIL import Image

if len(sys.argv) < 3:
    sys.stderr.write(__doc__)
    sys.exit(1)

src, out = sys.argv[1], sys.argv[2]
W = int(sys.argv[3]) if len(sys.argv) > 3 else 320
H = int(sys.argv[4]) if len(sys.argv) > 4 else 240

img = Image.open(src).convert("RGB")
# Letterbox into W×H so the aspect ratio of the original is preserved.
# Robot36 wants 4:3; if the source isn't, pad with black.
src_w, src_h = img.size
src_aspect = src_w / src_h
dst_aspect = W / H
if src_aspect > dst_aspect:
    new_w = W
    new_h = max(1, round(W / src_aspect))
else:
    new_h = H
    new_w = max(1, round(H * src_aspect))
img_scaled = img.resize((new_w, new_h), Image.LANCZOS)
canvas = Image.new("RGB", (W, H), (0, 0, 0))
canvas.paste(img_scaled, ((W - new_w) // 2, (H - new_h) // 2))

pixels = canvas.load()

with open(out, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/image_to_rgb565.py — do not edit. */\n")
    f.write(f"/* Source: {src} → {W}×{H} RGB565 (Robot36 native). */\n")
    f.write("#pragma once\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define TEST_IMAGE_W {W}\n")
    f.write(f"#define TEST_IMAGE_H {H}\n\n")
    f.write(f"static const uint16_t test_image_rgb565[{W} * {H}] = {{\n")
    for y in range(H):
        row = []
        for x in range(W):
            r, g, b = pixels[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            row.append(f"0x{v:04x}")
        # 16 values per line for readability
        for i in range(0, W, 16):
            chunk = ", ".join(row[i : i + 16])
            f.write(f"    {chunk},\n")
    f.write("};\n")

print(f"wrote {out}: {W}×{H} RGB565 = {W*H*2} bytes")
